import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ProvidersRedux } from "./store/ReduxProvider";
import ClientAuthGuard from "./ClientAuthGuard";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ProvidersRedux>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <ClientAuthGuard>{children}</ClientAuthGuard>
        </body>
      </ProvidersRedux>
    </html>
  );
}
